### ISSUE TITLE
Bad tag

### ISSUE THREAD

**Issue by cccs-dawson** [CybercentreCanada/assemblyline-service-apkaye#3]
The tag [here](https://github.com/CybercentreCanada/assemblyline-service-apkaye/blob/757c2f8e099b80f6255db2b42a5cac7daf30f992/apkaye/apkaye.py#L100) should be 'issuer' and not 'issues'

**Comment by cccs-jh** [comment]
Handled in #4. Thank you @cccs-dawson!
